Update star count
dev-protocol/onboarding-sponsor pull request #48
Opened 2021-07-24 08:42 UTC by talentlessguy

Some projects have earned some stars over time so this PR updates the list with more up-to-date stars

2021-07-30 04:28 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "372"
Hi sorry for the late reply. I have request:

**Update:**
- ffxiv-teamcraft/ffxiv-teamcraft - 374 stars

2021-07-30 04:28 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "133"
**Update:**
- bknds/ng-pi-admin - 135 stars

2021-07-30 04:31 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "752"
**Update:**
- napi-rs/napi-rs - 759 stars

2021-07-30 04:32 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "244"
**Update:**
- snapshot-labs/snapshot - 248 stars

2021-07-30 04:33 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "146"
**Update:**
- vignette-project/vignette - 147 stars

2021-07-30 04:34 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "151"
**Update:**
- lorcalhost/BTB-manager-telegram -158 stars

2021-07-30 04:35 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "512"
**Update:**
- ethereum-oasis/baseline - 513 stars

2021-07-30 04:36 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "574"
**Update:**
- nuxt-community/typescript-template - 575 stars

2021-07-30 04:37 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "821"
**Update:**
- eth-brownie/brownie - 832 stars

2021-07-30 04:38 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "130"
**Update:**
- 132 stars

2021-07-30 04:38 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "259"
**Update:**
- 263 stars

2021-07-30 04:39 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "528"
**Update:**
- 530 stars

2021-07-30 04:39 UTC, vinzvinci commented on assets/json/fundable_oss.json
> +    "stars_display": "179"
**Update:**
- 182 stars

2021-07-30 05:01 UTC, vinzvinci requested changes
We can't expect an increase of GitHub stars in their project. But I'll be watching this PR, I'll merge your next changes.

2021-07-30 07:22 UTC, talentlessguy commented
@vinzvinci wdym can't expect?

2021-07-30 07:27 UTC, vinzvinci commented
> @vinzvinci wdym can't expect?

stars are increasing anytime on the repository, but don't worry about it. Is it okay if u change the things I requested? 

--- 
- I created issues related to it #51 (coz we are manually adding numbers of star)

2021-07-30 07:46 UTC, talentlessguy commented
@vinzvinci yes it's ok

2021-07-30 09:11 UTC, talentlessguy commented
@vinzvinci done, I've updated all the stars

2021-07-31 03:05 UTC, vinzvinci commented
Hi @talentlessguy, thank you for your contributions, we decided not to merge PR for now, but your commits are still valid. Please look to other repositories `(there's a lot actually)`. I'll be closing this PR, please do understand.

**Reason:**
It depends on the developers of the sponsor's decision if they want to update their star.

2021-07-31 04:54 UTC, closed without merging

2021-07-31 08:17 UTC, talentlessguy commented
@vinzvinci wdym it depends on deve;oper of the sponsor's decision? those stars are not synced to github... and the JSON is static... so it's out of date

2021-07-31 08:30 UTC, vinzvinci commented
This means we can't change it without their consent. I also like to merge this but we need to follow the rules. 

Yes, the JSON is static that's why I created issue #51. Don't worry there's a lot of repositories you can contribute here, we're still updating many things little by little.